# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9wr0mJ0F5gEbIQtaiPYUhlpsJVuupyO
"""

import pandas as pd

# Load the dataset, handling errors
file_path = "/content/realistic_crispr_data.csv"
df = pd.read_csv(file_path, on_bad_lines='warn', delimiter=',', quoting=0)
# on_bad_lines='warn' will print a warning for problematic lines instead of raising an error immediately
# delimiter=',' explicitly sets the delimiter to a comma. Adjust if necessary.
# quoting=0 is equivalent to pd.QUOTE_MINIMAL and ensures that only fields
# with special characters like the delimiter are quoted

# Fill numerical columns with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# Fill numerical columns with median
df.fillna(df.median(numeric_only=True), inplace=True)

# Fill categorical columns with mode
for column in df.select_dtypes(include=['object']).columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

# Save the cleaned dataset
df.to_csv("/content/crispr_data.csv", index=False)

print("Missing values filled and dataset saved.")

import pandas as pd

# Load the dataset with error handling (Skipping bad rows)
file_path = "/content/realistic_crispr_data.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Save the cleaned dataset
cleaned_file_path = "/content/realistic_crispr_data_skipped_rows.csv"
df.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset while skipping bad rows
file_path = "/content/realistic_crispr_data_imputation.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Remove rows with any missing values
df_cleaned = df.dropna()
print("Rows with missing values removed.")

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print(f"Categorical columns found: {list(categorical_columns)}")

# Apply Label Encoding to categorical columns
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df_cleaned[col])
    label_encoders[col] = le

print("Categorical values converted to numerical.")

# Save the fully preprocessed dataset
processed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_cleaned.to_csv(processed_file_path, index=False)

print(f"Fully processed dataset saved at: {processed_file_path}")

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset while skipping bad rows
file_path = "/content/realistic_crispr_data_imputation.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Remove rows with any missing values
df_cleaned = df.dropna()
print("Rows with missing values removed.")

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print(f"Categorical columns found: {list(categorical_columns)}")

# Apply Label Encoding to categorical columns
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df_cleaned[col])
    label_encoders[col] = le

print("Categorical values converted to numerical.")

# Save the fully preprocessed dataset
processed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_cleaned.to_csv(processed_file_path, index=False)

print(f"Fully processed dataset saved at: {processed_file_path}")

# Function to replace outliers with median
def replace_outliers_with_median(df):
    for col in df.select_dtypes(include=[np.number]).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        median_value = df[col].median()

        df[col] = np.where((df[col] < lower_bound) | (df[col] > upper_bound), median_value, df[col])

    return df

df_imputed = replace_outliers_with_median(df)

# Save the dataset with outliers replaced
imputed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_imputed.to_csv(imputed_file_path, index=False)

print(f"Dataset with outliers replaced by median saved at: {imputed_file_path}")

