# -*- coding: utf-8 -*-
"""datapreparation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cAWWoW6RbCcTEtOyOuITiRL90IK4XXUF
"""

import random
import pandas as pd

# Generate random DNA sequences
def generate_dna_sequence(length=500):
    """Generates a random DNA sequence of a given length."""
    return ''.join(random.choices('ATCG', k=length))

# Introduce mutations into the DNA sequence with disease-specific mutation rules
def introduce_mutations(sequence, gene, mutation_rate=0.01):
    """Introduce mutations based on known mutation rates."""
    sequence = list(sequence)
    mutation_positions = random.sample(range(len(sequence)), int(len(sequence) * mutation_rate))

    for i in mutation_positions:
        if gene == 'CFTR' and random.random() < 0.1:
            # CFTR mutation pattern (common mutations)
            sequence[i] = 'C' if sequence[i] != 'C' else 'G'
        elif gene == 'BRCA1' and random.random() < 0.05:
            # BRCA1 mutation pattern (common mutations)
            sequence[i] = 'T' if sequence[i] != 'T' else 'A'
        elif gene == 'TP53' and random.random() < 0.03:
            # TP53 mutation pattern (common mutations)
            sequence[i] = 'A' if sequence[i] != 'A' else 'G'
        else:
            sequence[i] = random.choice('ATCG'.replace(sequence[i], ''))

    return ''.join(sequence)

# Function to assign diseases based on mutation patterns (simplified)
def assign_disease(sequence, gene):
    """Assign a disease label based on certain mutation patterns in the sequence."""
    disease_associations = {
        'BRCA1': 'Breast Cancer',
        'CFTR': 'Cystic Fibrosis',
        'APOE': 'Alzheimer’s Disease',
        'TP53': 'Lung Cancer',
        'EGFR': 'Non-Small Cell Lung Cancer'
    }
    if gene == 'CFTR' and 'G' in sequence[:50]:  # Example rule for CFTR
        return disease_associations.get(gene, 'No Disease')
    elif gene == 'BRCA1' and 'T' in sequence[100:150]:  # Example rule for BRCA1
        return disease_associations.get(gene, 'No Disease')
    else:
        return 'No Disease'

# Find CRISPR targets (PAM sites)
def find_crispr_targets(sequence, pam="GG"):
    """Finds CRISPR target sequences by identifying PAM sites."""
    targets = []
    for i in range(len(sequence) - 2):
        if sequence[i:i+2] == pam:
            targets.append(sequence[max(0, i-20):i+23])  # Include 20 bp upstream and 3 bp PAM
    return targets

# Generate efficiency scores for gRNAs
def generate_efficiency_scores(targets):
    """Generates efficiency scores for each gRNA target sequence."""
    return {target: random.uniform(0.5, 1.0) for target in targets}

# Simulate epigenetic data (methylation patterns and gene expression)
def generate_epigenetic_data(gene):
    """Generate random epigenetic data such as methylation and gene expression."""
    methylation = random.uniform(0.0, 1.0)
    gene_expression = random.uniform(0.5, 2.0)  # Simulating gene expression levels
    return methylation, gene_expression

# Generate clinical and environmental data
def generate_clinical_data():
    """Generate random clinical data for a synthetic patient."""
    ages = [random.randint(20, 80) for _ in range(10)]  # Random ages between 20 and 80
    gender = random.choice(['Male', 'Female'])
    ethnicity = random.choice(['Caucasian', 'African American', 'Asian', 'Hispanic'])
    return random.choice(ages), gender, ethnicity

# Generate environmental data
def generate_environmental_data():
    """Generate random environmental data."""
    smoking_history = random.choice(['Smoker', 'Non-smoker'])
    exercise_frequency = random.choice(['Low', 'Medium', 'High'])
    diet = random.choice(['High-fat', 'Balanced', 'Low-fat'])
    pollution_level = random.choice(['Low', 'Medium', 'High'])
    allergen_exposure = random.choice(['Low', 'Medium', 'High'])
    return smoking_history, exercise_frequency, diet, pollution_level, allergen_exposure

# Generate synthetic data with sequences, diseases, and CRISPR targets
synthetic_sequences = [generate_dna_sequence() for _ in range(1000)]  # 1000 sequences
mutated_sequences = []

# Gene-Disease Associations (for demonstration)
genes = ['BRCA1', 'CFTR', 'APOE', 'TP53', 'EGFR']

labeled_data = []

# Assign diseases, CRISPR targets, efficiency scores, and clinical data to the sequences
for seq in synthetic_sequences:
    gene = random.choice(genes)  # Randomly assign a gene
    mutated_seq = introduce_mutations(seq, gene)
    disease = assign_disease(mutated_seq, gene)
    gRNA_targets = find_crispr_targets(mutated_seq)

    # Generate clinical and environmental data
    age, gender, ethnicity = generate_clinical_data()
    smoking_history, exercise_frequency, diet, pollution_level, allergen_exposure = generate_environmental_data()

    # Generate epigenetic data (methylation and gene expression)
    methylation, gene_expression = generate_epigenetic_data(gene)

    mutation_type = random.choice(['SNP', 'Indel', 'CNV'])
    pathogenicity = random.choice(['High', 'Moderate', 'Low'])

    # Generate drug response and side effects
    drug_response = random.choice(['Effective', 'Ineffective'])
    side_effects = random.choice(['None', 'Mild', 'Moderate', 'Severe'])

    # Treatment Duration (months)
    treatment_duration = random.randint(1, 12)  # Random treatment duration between 1 and 12 months

    # Gene therapy feasibility
    gene_therapy_feasibility = random.choice(['Possible', 'Not Possible'])

    # Add biological noise (random variations to mimic sequencing errors)
    noise_level = random.uniform(0, 0.05)  # Noise level between 0% and 5% variation

    # Apply noise to the gene expression levels
    gene_expression_noisy = gene_expression + (random.choice([-1, 1]) * noise_level)

    # Check if gRNA targets exist before proceeding
    if gRNA_targets:
        efficiency_scores = generate_efficiency_scores(gRNA_targets)
        labeled_data.append({
            'patient_id': f'P{random.randint(1000, 9999)}',
            'sequence': mutated_seq,
            'gene': gene,
            'chromosomal_location': f'{random.randint(1, 22)}q{random.randint(1, 2)}.1',
            'mutation_type': mutation_type,
            'mutation_position': random.randint(1, 500),
            'mutation_effect': 'Loss-of-function' if random.random() > 0.5 else 'Gain-of-function',
            'disease': disease,
            'pathogenicity': pathogenicity,
            'efficiency_scores': efficiency_scores,
            'gRNA_targets': gRNA_targets,
            'age': age,
            'gender': gender,
            'ethnicity': ethnicity,
            'smoking_history': smoking_history,
            'exercise_frequency': exercise_frequency,
            'diet': diet,
            'pollution_level': pollution_level,
            'allergen_exposure': allergen_exposure,
            'drug_response': drug_response,
            'side_effects': side_effects,
            'treatment_duration': treatment_duration,
            'gene_therapy_feasibility': gene_therapy_feasibility,
            'clinical_history': ['No known conditions'] if random.random() > 0.7 else ['Chronic disease'],
            'family_history': ['Cancer', 'Heart disease'] if random.random() > 0.6 else ['None'],
            'gene_expression': gene_expression_noisy,
            'epigenetic_data': {'methylation': methylation}
        })
    else:
        # If no gRNA targets found, store empty lists for those fields
        labeled_data.append({
            'patient_id': f'P{random.randint(1000, 9999)}',
            'sequence': mutated_seq,
            'gene': gene,
            'chromosomal_location': f'{random.randint(1, 22)}q{random.randint(1, 2)}.1',
            'mutation_type': mutation_type,
            'mutation_position': random.randint(1, 500),
            'mutation_effect': 'Loss-of-function' if random.random() > 0.5 else 'Gain-of-function',
            'disease': disease,
            'pathogenicity': pathogenicity,
            'efficiency_scores': [],
            'gRNA_targets': [],
            'age': age,
            'gender': gender,
            'ethnicity': ethnicity,
            'smoking_history': smoking_history,
            'exercise_frequency': exercise_frequency,
            'diet': diet,
            'pollution_level': pollution_level,
            'allergen_exposure': allergen_exposure,
            'drug_response': drug_response,
            'side_effects': side_effects,
            'treatment_duration': treatment_duration,
            'gene_therapy_feasibility': gene_therapy_feasibility,
            'clinical_history': ['No known conditions'],
            'family_history': ['None'],
            'gene_expression': gene_expression_noisy,
            'epigenetic_data': {'methylation': methylation}
        })

# Convert to DataFrame
df = pd.DataFrame(labeled_data)

# Save to CSV
df.to_csv('synthetic_crispr_disease_data_realistic.csv', index=False)

print("Data saved to 'synthetic_crispr_disease_data_realistic.csv'")

# prompt: PRINT ITS METADATA

import pandas as pd

# Load the dataframe
df = pd.read_csv('synthetic_crispr_disease_data_realistic.csv')

# Print metadata (column names and data types)
print(df.info())

# Print some descriptive statistics
print(df.describe())

import pandas as pd

# Load the dataframe
df = pd.read_csv('synthetic_crispr_disease_data_realistic.csv')

# Check for missing values in each column
missing_values = df.isnull().sum()

# Print the columns with missing values and their counts
print(missing_values[missing_values > 0])

import missingno as msno
import matplotlib.pyplot as plt

# Install missingno if you haven't already:
# !pip install missingno

# Visualize missing values using a matrix plot
msno.matrix(df)
plt.show()

# Visualize missing values using a bar chart
msno.bar(df)
plt.show()

# prompt: HANDLE MISSING VALUE USING MEAN

# Fill missing values in 'gene_expression' with the mean
df['gene_expression'].fillna(df['gene_expression'].mean(), inplace=True)

