# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-9wr0mJ0F5gEbIQtaiPYUhlpsJVuupyO
"""

import pandas as pd

# Load the dataset, handling errors
file_path = "/content/realistic_crispr_data.csv"
df = pd.read_csv(file_path, on_bad_lines='warn', delimiter=',', quoting=0)
# on_bad_lines='warn' will print a warning for problematic lines instead of raising an error immediately
# delimiter=',' explicitly sets the delimiter to a comma. Adjust if necessary.
# quoting=0 is equivalent to pd.QUOTE_MINIMAL and ensures that only fields
# with special characters like the delimiter are quoted

# Fill numerical columns with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# Fill numerical columns with median
df.fillna(df.median(numeric_only=True), inplace=True)

# Fill categorical columns with mode
for column in df.select_dtypes(include=['object']).columns:
    df[column].fillna(df[column].mode()[0], inplace=True)

# Save the cleaned dataset
df.to_csv("/content/crispr_data.csv", index=False)

print("Missing values filled and dataset saved.")

import pandas as pd

# Load the dataset with error handling (Skipping bad rows)
file_path = "/content/realistic_crispr_data.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Save the cleaned dataset
cleaned_file_path = "/content/realistic_crispr_data_skipped_rows.csv"
df.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset while skipping bad rows
file_path = "/content/realistic_crispr_data_imputation.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Remove rows with any missing values
df_cleaned = df.dropna()
print("Rows with missing values removed.")

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print(f"Categorical columns found: {list(categorical_columns)}")

# Apply Label Encoding to categorical columns
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df_cleaned[col])
    label_encoders[col] = le

print("Categorical values converted to numerical.")

# Save the fully preprocessed dataset
processed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_cleaned.to_csv(processed_file_path, index=False)

print(f"Fully processed dataset saved at: {processed_file_path}")

import pandas as pd
from sklearn.preprocessing import LabelEncoder

# Load the dataset while skipping bad rows
file_path = "/content/realistic_crispr_data_imputation.csv"
df = pd.read_csv(file_path, on_bad_lines='skip')

print("Dataset loaded successfully with problematic rows skipped.")

# Remove rows with any missing values
df_cleaned = df.dropna()
print("Rows with missing values removed.")

# Identify categorical columns
categorical_columns = df_cleaned.select_dtypes(include=['object']).columns
print(f"Categorical columns found: {list(categorical_columns)}")

# Apply Label Encoding to categorical columns
label_encoders = {}
for col in categorical_columns:
    le = LabelEncoder()
    df_cleaned[col] = le.fit_transform(df_cleaned[col])
    label_encoders[col] = le

print("Categorical values converted to numerical.")

# Save the fully preprocessed dataset
processed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_cleaned.to_csv(processed_file_path, index=False)

print(f"Fully processed dataset saved at: {processed_file_path}")

# Function to replace outliers with median
def replace_outliers_with_median(df):
    for col in df.select_dtypes(include=[np.number]).columns:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)
        IQR = Q3 - Q1
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR

        median_value = df[col].median()

        df[col] = np.where((df[col] < lower_bound) | (df[col] > upper_bound), median_value, df[col])

    return df

df_imputed = replace_outliers_with_median(df)

# Save the dataset with outliers replaced
imputed_file_path = "/content/realistic_crispr_data_nominal converion.csv"
df_imputed.to_csv(imputed_file_path, index=False)

print(f"Dataset with outliers replaced by median saved at: {imputed_file_path}")

import pandas as pd

# Load the dataset
file_path = "/content/realistic_crispr_data_outlier imputation.csv"
df = pd.read_csv(file_path)

# Remove duplicates
df_cleaned = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "/content/crispr_data_duplicates removed.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Duplicates removed. Cleaned file saved at: {cleaned_file_path}")

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold, mutual_info_classif
from sklearn.preprocessing import LabelEncoder

# Load the dataset
file_path = "/content/crispr_data_duplicates removed.csv"
df = pd.read_csv(file_path)

# Drop patient_id and sequence (since they are identifiers)
df = df.drop(columns=["patient_id", ], errors="ignore")

# Remove rows where 'disease' is missing
df = df.dropna(subset=['disease'])

# Encode categorical variables
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Split features and target
X = df.drop(columns=['disease'])
y = df['disease']

### 1️⃣ Identify Low Variance Features
var_thresh = VarianceThreshold(threshold=0.01)  # Features with variance < 0.01 are removed
low_variance_mask = var_thresh.fit(X)
low_variance_features = X.columns[~low_variance_mask.get_support()]

### 2️⃣ Identify Highly Correlated Features
correlation_matrix = X.corr().abs()
high_correlation_pairs = []
correlation_threshold = 0.85

for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if correlation_matrix.iloc[i, j] > correlation_threshold:
            high_correlation_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

# Create a list of features to consider removing (keeping only one from correlated pairs)
correlated_features = set([pair[1] for pair in high_correlation_pairs])

### 3️⃣ Feature Importance using Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X, y)
feature_importance = pd.Series(rf_model.feature_importances_, index=X.columns)

# Low-importance features (threshold = 0.01)
low_importance_features = feature_importance[feature_importance < 0.01].index.tolist()

# Combine all features to ignore
features_to_ignore = set(low_variance_features) | correlated_features | set(low_importance_features)

# Save ignored features
ignored_features_file = "/content/crispr_data.csv"
pd.DataFrame({"Ignored_Features": list(features_to_ignore)}).to_csv(ignored_features_file, index=False)

print(f"Ignored features saved at: {ignored_features_file}")

import pandas as pd

# Load the dataset
file_path = "/content/crispr_data_duplicates removed.csv"
df = pd.read_csv(file_path)

# Load the ignored features list
ignored_features_file = "/content/crispr_data.csv"
ignored_features = pd.read_csv(ignored_features_file)["Ignored_Features"].tolist()

# Drop the identified useless features
df_cleaned = df.drop(columns=ignored_features, errors="ignore")

# Save the cleaned dataset
cleaned_file_path = "/content/crispr_data_(11).csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")

import pandas as pd
df.drop(columns=['patient_id'])
cleaned_file_path = "/content/crispr_data_(1111).csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")