# -*- coding: utf-8 -*-
"""Untitled39.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Lqz38EXGVD-a3XU17ZEyWWsMM5vhXzJX
"""

import pandas as pd

# Load the dataset
file_path = "/content/realistic_crispr_data_outlier imputation.csv"
df = pd.read_csv(file_path)

# Remove duplicates
df_cleaned = df.drop_duplicates()

# Save the cleaned dataset
cleaned_file_path = "/content/crispr_data_duplicates removed.csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Duplicates removed. Cleaned file saved at: {cleaned_file_path}")

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import VarianceThreshold, mutual_info_classif
from sklearn.preprocessing import LabelEncoder

# Load the dataset
file_path = "/content/crispr_data_duplicates removed.csv"
df = pd.read_csv(file_path)

# Drop patient_id and sequence (since they are identifiers)
df = df.drop(columns=["patient_id", ], errors="ignore")

# Remove rows where 'disease' is missing
df = df.dropna(subset=['disease'])

# Encode categorical variables
label_encoders = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoders[col] = le

# Split features and target
X = df.drop(columns=['disease'])
y = df['disease']

### 1️⃣ Identify Low Variance Features
var_thresh = VarianceThreshold(threshold=0.01)  # Features with variance < 0.01 are removed
low_variance_mask = var_thresh.fit(X)
low_variance_features = X.columns[~low_variance_mask.get_support()]

### 2️⃣ Identify Highly Correlated Features
correlation_matrix = X.corr().abs()
high_correlation_pairs = []
correlation_threshold = 0.85

for i in range(len(correlation_matrix.columns)):
    for j in range(i):
        if correlation_matrix.iloc[i, j] > correlation_threshold:
            high_correlation_pairs.append((correlation_matrix.columns[i], correlation_matrix.columns[j]))

# Create a list of features to consider removing (keeping only one from correlated pairs)
correlated_features = set([pair[1] for pair in high_correlation_pairs])

### 3️⃣ Feature Importance using Random Forest
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X, y)
feature_importance = pd.Series(rf_model.feature_importances_, index=X.columns)

# Low-importance features (threshold = 0.01)
low_importance_features = feature_importance[feature_importance < 0.01].index.tolist()

# Combine all features to ignore
features_to_ignore = set(low_variance_features) | correlated_features | set(low_importance_features)

# Save ignored features
ignored_features_file = "/content/crispr_data.csv"
pd.DataFrame({"Ignored_Features": list(features_to_ignore)}).to_csv(ignored_features_file, index=False)

print(f"Ignored features saved at: {ignored_features_file}")

import pandas as pd

# Load the dataset
file_path = "/content/crispr_data_duplicates removed.csv"
df = pd.read_csv(file_path)

# Load the ignored features list
ignored_features_file = "/content/crispr_data.csv"
ignored_features = pd.read_csv(ignored_features_file)["Ignored_Features"].tolist()

# Drop the identified useless features
df_cleaned = df.drop(columns=ignored_features, errors="ignore")

# Save the cleaned dataset
cleaned_file_path = "/content/crispr_data_(11).csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")

import pandas as pd
df.drop(columns=['patient_id'])
cleaned_file_path = "/content/crispr_data_(1111).csv"
df_cleaned.to_csv(cleaned_file_path, index=False)

print(f"Cleaned dataset saved at: {cleaned_file_path}")

from sklearn.feature_selection import f_regression, SelectKBest

selector = SelectKBest(score_func=f_regression, k=5)  # Select top 5 best features
X_selected = selector.fit_transform(X, y)
selected_features = X.columns[selector.get_support()]
print("Selected Features:", selected_features.tolist())

from sklearn.tree import DecisionTreeRegressor

tree_reg = DecisionTreeRegressor(max_depth=5)
tree_reg.fit(X_train, y_train)
y_pred_tree = tree_reg.predict(X_test)

print("Decision Tree R²:", r2_score(y_test, y_pred_tree))

from sklearn.ensemble import RandomForestRegressor

rf_reg = RandomForestRegressor(n_estimators=100, random_state=42)
rf_reg.fit(X_train, y_train)
y_pred_rf = rf_reg.predict(X_test)

print("Random Forest R²:", r2_score(y_test, y_pred_rf))

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

selector = SelectKBest(score_func=f_regression, k=10)  # Select top 10 features
X_selected = selector.fit_transform(X, y)
selected_features = X.columns[selector.get_support()]
print("✅ Selected Features:", selected_features.tolist())

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PolynomialFeatures
from sklearn.feature_selection import SelectKBest, f_regression
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor  # Install with: pip install xgboost
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load the dataset
file_path = "/content/crispr_data_(1111).csv"
df = pd.read_csv(file_path)

# Drop missing values (or use imputation instead)
df.dropna(inplace=True)

# Selecting numerical features only
df_numeric = df.select_dtypes(include=['number'])

# Ensure the target variable ('disease') is present
if 'disease' not in df_numeric.columns:
    raise ValueError("Target variable 'disease' not found in dataset!")

# Define target (y) and features (X)
X = df_numeric.drop(columns=['disease'])  # Features
y = df_numeric['disease']  # Target variable

# Feature Selection: Keep only the top 10 important features
selector = SelectKBest(score_func=f_regression, k=10)
X_selected = selector.fit_transform(X, y)
selected_features = X.columns[selector.get_support()]
print("✅ Selected Features:", selected_features.tolist())

# Split dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_selected, y, test_size=0.2, random_state=42)

# Standardization (Scaling)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Polynomial Features (Degree = 2 for Non-Linear Patterns)
poly = PolynomialFeatures(degree=2)
X_train_poly = poly.fit_transform(X_train_scaled)
X_test_poly = poly.transform(X_test_scaled)

# 1️⃣ Linear Regression
lin_reg = LinearRegression()
lin_reg.fit(X_train_scaled, y_train)
y_pred_lin = lin_reg.predict(X_test_scaled)

# 2️⃣ Decision Tree Regression
tree_reg = DecisionTreeRegressor(max_depth=5)
tree_reg.fit(X_train_scaled, y_train)
y_pred_tree = tree_reg.predict(X_test_scaled)

# 3️⃣ Hyperparameter Tuned Random Forest Regression
rf_reg = RandomForestRegressor(n_estimators=200, max_depth=10, random_state=42)
rf_reg.fit(X_train_scaled, y_train)
y_pred_rf = rf_reg.predict(X_test_scaled)

# 4️⃣ XGBoost Regression
xgb_reg = XGBRegressor(n_estimators=200, learning_rate=0.1, max_depth=6, random_state=42)
xgb_reg.fit(X_train_scaled, y_train)
y_pred_xgb = xgb_reg.predict(X_test_scaled)

# Evaluation Function
def evaluate_model(model_name, y_test, y_pred):
    print(f"\n🔹 {model_name} Results:")
    print("R² Score:", r2_score(y_test, y_pred))
    print("MAE:", mean_absolute_error(y_test, y_pred))
    print("MSE:", mean_squared_error(y_test, y_pred))

# Print Results
evaluate_model("Linear Regression", y_test, y_pred_lin)
evaluate_model("Decision Tree", y_test, y_pred_tree)
evaluate_model("Random Forest (Tuned)", y_test, y_pred_rf)
evaluate_model("XGBoost", y_test, y_pred_xgb)

import optuna
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Load your data
df = pd.read_csv("/content/crispr_data_(1111).csv")
X = df.drop("disease", axis=1)  # Assuming "disease" is your target variable
y = df["disease"]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Objective function for Optuna
def objective(trial):
    params = {
        "n_estimators": trial.suggest_int("n_estimators", 100, 1000, step=50),
        "learning_rate": trial.suggest_loguniform("learning_rate", 0.01, 0.3),
        "max_depth": trial.suggest_int("max_depth", 3, 12),
        "subsample": trial.suggest_uniform("subsample", 0.5, 1.0),
        "colsample_bytree": trial.suggest_uniform("colsample_bytree", 0.5, 1.0),
        "reg_lambda": trial.suggest_loguniform("reg_lambda", 1e-3, 10.0),
        "reg_alpha": trial.suggest_loguniform("reg_alpha", 1e-3, 10.0),
    }

    model = xgb.XGBRegressor(**params, random_state=42)
    model.fit(X_train, y_train)
    preds = model.predict(X_test)
    return mean_squared_error(y_test, preds)

# Running Optuna
study = optuna.create_study(direction="minimize")
study.optimize(objective, n_trials=50)

# Train the best model
best_params = study.best_params
optimized_model = xgb.XGBRegressor(**best_params, random_state=42)
optimized_model.fit(X_train, y_train)
y_pred = optimized_model.predict(X_test)

# Evaluate
print("Optimized XGBoost Results:")
print("R² Score:", r2_score(y_test, y_pred))
print("MAE:", mean_absolute_error(y_test, y_pred))
print("MSE:", mean_squared_error(y_test, y_pred))

import lightgbm as lgb
import catboost as cb

# LightGBM
lgb_model = lgb.LGBMRegressor()
lgb_model.fit(X_train, y_train)
lgb_preds = lgb_model.predict(X_test)

print("LightGBM Results:")
print("R² Score:", r2_score(y_test, lgb_preds))
print("MAE:", mean_absolute_error(y_test, lgb_preds))
print("MSE:", mean_squared_error(y_test, lgb_preds))

# CatBoost
cb_model = cb.CatBoostRegressor(verbose=0)
cb_model.fit(X_train, y_train)
cb_preds = cb_model.predict(X_test)

print("CatBoost Results:")
print("R² Score:", r2_score(y_test, cb_preds))
print("MAE:", mean_absolute_error(y_test, cb_preds))
print("MSE:", mean_squared_error(y_test, cb_preds))

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Load dataset
file_path = "crispr_data_(1111).csv"  # Update if needed
data = pd.read_csv(file_path)

# Drop duplicates & handle missing values
data = data.drop_duplicates()
data = data.fillna(data.mean())

# Convert categorical variables
data = pd.get_dummies(data, drop_first=True)

# Drop highly correlated features
corr_matrix = data.corr().abs()
high_corr_features = set()
threshold = 0.9

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if corr_matrix.iloc[i, j] > threshold:
            colname = corr_matrix.columns[i]
            high_corr_features.add(colname)

data = data.drop(columns=high_corr_features)

# Define X and y
X = data.drop(columns=['disease'])  # Assuming "disease" is the target
y = data['disease']

# Apply SMOTE (handle class imbalance)
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Scale data
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 🔥 Hyperparameter Tuning with GridSearchCV
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

rf_model = RandomForestClassifier(random_state=42)

grid_search = GridSearchCV(rf_model, param_grid, cv=5, n_jobs=-1, scoring='accuracy', verbose=2)
grid_search.fit(X_train, y_train)

# Best Model
best_rf = grid_search.best_estimator_

# Predictions
y_pred = best_rf.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"🔥 Optimized Random Forest Accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred))

# Confusion Matrix
ConfusionMatrixDisplay.from_estimator(best_rf, X_test, y_test, cmap="Blues")
plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, ConfusionMatrixDisplay
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt

# Load dataset
file_path = "crispr_data_(1111).csv"  # Update path if needed
data = pd.read_csv(file_path)

# Drop duplicates & handle missing values
data = data.drop_duplicates()
data = data.fillna(data.mean())

# Convert categorical variables to numerical
data = pd.get_dummies(data, drop_first=True)

# Drop highly correlated features
corr_matrix = data.corr().abs()
high_corr_features = set()
threshold = 0.9

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if corr_matrix.iloc[i, j] > threshold:
            colname = corr_matrix.columns[i]
            high_corr_features.add(colname)

data = data.drop(columns=high_corr_features)

# Define X and y
X = data.drop(columns=['disease'])  # Assuming "disease" is the target
y = data['disease']

# Handle class imbalance using SMOTE
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split data
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, random_state=42)

# Scale the data (Naïve Bayes is sensitive to large values)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 🔥 Train Naïve Bayes Classifier
nb_model = GaussianNB()
nb_model.fit(X_train, y_train)

# Predictions
y_pred = nb_model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"🔥 Naïve Bayes Accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred))

# Confusion Matrix
ConfusionMatrixDisplay.from_estimator(nb_model, X_test, y_test, cmap="Blues")
plt.show()

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, classification_report
from imblearn.over_sampling import SMOTE
import matplotlib.pyplot as plt
from sklearn.metrics import ConfusionMatrixDisplay

# Load dataset
file_path = "crispr_data_(1111).csv"  # Update if needed
data = pd.read_csv(file_path)

# Drop highly correlated features
corr_matrix = data.corr().abs()
high_corr_features = set()
threshold = 0.85  # Lowered threshold to remove even slightly high correlations

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if corr_matrix.iloc[i, j] > threshold:
            colname = corr_matrix.columns[i]
            high_corr_features.add(colname)

data = data.drop(columns=high_corr_features)

# Define X and y
X = data.drop(columns=['disease'])  # Assuming "disease" is the target
y = data['disease']

# Apply SMOTE to handle class imbalance
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split data (Stratified Sampling)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, stratify=y_resampled, random_state=42)

# 🔹 Use MinMaxScaler (better for KNN than StandardScaler)
scaler = MinMaxScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 🔍 Hyperparameter tuning for KNN
param_grid = {
    'n_neighbors': [3, 5, 7, 9, 11, 15],   # Try more values
    'weights': ['uniform', 'distance'],    # Distance-based weights can help
    'metric': ['euclidean', 'manhattan', 'minkowski']  # Try different distance metrics
}

grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best Parameters
best_params = grid_search.best_params_
print(f"✅ Best Parameters: {best_params}")

# 🔥 Train KNN with best parameters
knn_model = KNeighborsClassifier(**best_params)
knn_model.fit(X_train, y_train)

# Predictions
y_pred = knn_model.predict(X_test)

# Evaluate
accuracy = accuracy_score(y_test, y_pred)
print(f"🔥 Improved KNN Accuracy: {accuracy:.4f}")
print(classification_report(y_test, y_pred))

# Confusion Matrix
ConfusionMatrixDisplay.from_estimator(knn_model, X_test, y_test, cmap="Blues")
plt.show()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import MinMaxScaler, PolynomialFeatures
from sklearn.decomposition import PCA
from sklearn.feature_selection import RFE
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, VotingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from imblearn.over_sampling import SMOTE

# 🔹 Load dataset
file_path = "crispr_data_(1111).csv"
data = pd.read_csv(file_path)

# Drop highly correlated features
corr_matrix = data.corr().abs()
high_corr_features = set()
threshold = 0.8

for i in range(len(corr_matrix.columns)):
    for j in range(i):
        if corr_matrix.iloc[i, j] > threshold:
            colname = corr_matrix.columns[i]
            high_corr_features.add(colname)

data = data.drop(columns=high_corr_features)

# Define X and y
X = data.drop(columns=['disease'])
y = data['disease']

# 🔥 Apply SMOTE for class balancing
smote = SMOTE(random_state=42)
X_resampled, y_resampled = smote.fit_resample(X, y)

# Split dataset (Stratified Sampling)
X_train, X_test, y_train, y_test = train_test_split(X_resampled, y_resampled, test_size=0.2, stratify=y_resampled, random_state=42)

# 🔥 Feature Engineering (Polynomial Features)
poly = PolynomialFeatures(degree=2, interaction_only=True, include_bias=False)
X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

# 🔥 Feature Selection (Recursive Feature Elimination)
rf = RandomForestClassifier(n_estimators=50, random_state=42)
rfe = RFE(rf, n_features_to_select=20)  # Keep only top 20 features
X_train_rfe = rfe.fit_transform(X_train_poly, y_train)
X_test_rfe = rfe.transform(X_test_poly)

# 🔥 Apply MinMaxScaler
scaler = MinMaxScaler()
X_train_scaled = scaler.fit_transform(X_train_rfe)
X_test_scaled = scaler.transform(X_test_rfe)

# 🔹 PCA for Noise Reduction (Keep 95% Variance)
pca = PCA(n_components=0.95, random_state=42)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca = pca.transform(X_test_scaled)

# 🔍 Hyperparameter Tuning for KNN
param_grid = {
    'n_neighbors': range(3, 25, 2),  # Increased range
    'weights': ['uniform', 'distance'],
    'metric': ['euclidean', 'manhattan', 'minkowski']
}
grid_search = GridSearchCV(KNeighborsClassifier(), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train_pca, y_train)

# ✅ Best KNN Model
best_knn = grid_search.best_estimator_
print("\n✅ Best KNN Parameters:", grid_search.best_params_)

# 🔥 Bagging Classifier (Boost KNN Performance)
bagging_knn = BaggingClassifier(estimator=best_knn, n_estimators=50, random_state=42)
bagging_knn.fit(X_train_pca, y_train)

# 🔥 Random Forest Classifier for Ensemble Learning
rf_model = RandomForestClassifier(n_estimators=200, max_depth=20, random_state=42)
rf_model.fit(X_train_pca, y_train)

# 🔥 Voting Classifier (Hybrid Model: KNN + RF)
voting_clf = VotingClassifier(estimators=[('knn', bagging_knn), ('rf', rf_model)], voting='soft')
voting_clf.fit(X_train_pca, y_train)

# ✅ Make Predictions
y_pred = voting_clf.predict(X_test_pca)

# 📊 Evaluate Performance
accuracy = accuracy_score(y_test, y_pred)
print(f"\n🔥 Final Hybrid Model Accuracy: {accuracy:.4f}")
print("\n📌 Classification Report:\n", classification_report(y_test, y_pred))

# 🎯 Confusion Matrix
plt.figure(figsize=(6, 5))
sns.heatmap(confusion_matrix(y_test, y_pred), annot=True, fmt='d', cmap="Blues")
plt.title("Confusion Matrix - Optimized KNN + RandomForest")
plt.xlabel("Predicted Label")
plt.ylabel("True Label")
plt.show()

from sklearn.ensemble import RandomForestClassifier

# Re-train the model if necessary
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)  # Ensure X_train, y_train are correctly defined

# Now, extract feature importances
importances = rf_model.feature_importances_
feature_names = X.columns
feature_importance_df = pd.DataFrame({"Feature": feature_names, "Importance": importances})
feature_importance_df = feature_importance_df.sort_values(by="Importance", ascending=False)

# Plot feature importance
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
sns.barplot(x="Importance", y="Feature", data=feature_importance_df.head(10), palette="viridis")
plt.title("Top 10 Feature Importances in Random Forest")
plt.show()

from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier

# Define parameter grid for tuning
param_grid = {
    'n_estimators': [50, 100, 200],
    'max_depth': [None, 10, 20],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

# Perform Grid Search
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=3, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Print Best Parameters
print(f"Best Parameters: {grid_search.best_params_}")
best_model = grid_search.best_estimator_

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

# Train Gradient Boosting Model
gb_model = GradientBoostingClassifier(n_estimators=100, random_state=42)
gb_model.fit(X_train, y_train)

# Predictions
y_pred_gb = gb_model.predict(X_test)

# Evaluate
print(f"Gradient Boosting Accuracy: {accuracy_score(y_test, y_pred_gb):.4f}")
print(classification_report(y_test, y_pred_gb))

from sklearn.model_selection import GridSearchCV

# Define parameter grid
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, None],
    'min_samples_split': [2, 5, 10]
}

# Grid search for hyperparameter tuning
grid_search = GridSearchCV(RandomForestClassifier(random_state=42), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(X_train, y_train)

# Best model
best_rf_model = grid_search.best_estimator_
print(f"Best Parameters: {grid_search.best_params_}")

import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.neural_network import MLPClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.metrics import accuracy_score, classification_report

# Train Neural Network Model
nn_model = MLPClassifier(hidden_layer_sizes=(64, 32), activation='relu', solver='adam', max_iter=300, random_state=42)
nn_model.fit(X_train, y_train)

# Predictions
y_pred_nn = nn_model.predict(X_test)

# Evaluate
print(f"🔹 Neural Network Accuracy: {accuracy_score(y_test, y_pred_nn):.4f}")
print(classification_report(y_test, y_pred_nn))

# Train XGBoost Model
xgb_model = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
xgb_model.fit(X_train, y_train)

# Predictions
y_pred_xgb = xgb_model.predict(X_test)

# Evaluate
print(f"🔹 XGBoost Accuracy: {accuracy_score(y_test, y_pred_xgb):.4f}")
print(classification_report(y_test, y_pred_xgb))

# Train SVM Model
svm_model = SVC(kernel='rbf', C=1.0, random_state=42)
svm_model.fit(X_train, y_train)

# Predictions
y_pred_svm = svm_model.predict(X_test)

# Evaluate
print(f"🔹 SVM Accuracy: {accuracy_score(y_test, y_pred_svm):.4f}")
print(classification_report(y_test, y_pred_svm))

