# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J9kfh5pmmyC7w2JPjiRl3coihHi3jzxR
"""

import pandas as pd
import numpy as np

# Load the dataset
file_path = "/content/synthetic_crispr_disease_data_realistic.csv"
df = pd.read_csv(file_path)

# Adjust mutation types with real-world variability
mutation_types = ['Missense', 'Nonsense', 'Frameshift', 'Splice-site', 'Silent', 'Insertion', 'Deletion']
df['mutation_type'] = np.random.choice(mutation_types, size=len(df), p=[0.3, 0.2, 0.15, 0.1, 0.05, 0.1, 0.1])

# Adjust gene names to realistic ones (adding variety)
genes = ['TP53', 'CFTR', 'EGFR', 'BRCA1', 'BRCA2', 'KRAS', 'BRAF', 'MYC']
df['gene'] = np.random.choice(genes, size=len(df))

# Adjust mutation positions with realistic ranges
df['mutation_position'] = np.random.randint(50, 4000, size=len(df))

# Introduce real-world pathogenicity scores (0-1 probability)
df['pathogenicity_score'] = np.random.uniform(0.05, 0.99, size=len(df)).round(2)

# Adjust efficiency scores to be non-uniform
df['efficiency_score'] = np.random.normal(loc=0.7, scale=0.15, size=len(df)).clip(0, 1).round(2)

# Introduce epigenetic data with some missing values
df['epigenetic_marker'] = np.random.choice([1, 2, 3, np.nan], size=len(df), p=[0.3, 0.3, 0.3, 0.1])

# Adjust disease labels for more diversity
diseases = ['Cystic Fibrosis', 'Lung Cancer', 'Breast Cancer', 'Colon Cancer', 'Leukemia', 'None']
df['disease'] = np.random.choice(diseases, size=len(df), p=[0.2, 0.2, 0.15, 0.15, 0.1, 0.2])

# Introduce missing values in some key columns
for col in ['mutation_type', 'gene', 'pathogenicity_score', 'efficiency_score']:
    df.loc[df.sample(frac=0.05).index, col] = np.nan  # 5% missing values

# Save the modified dataset
modified_file_path = "/content/realistic_crispr_disease_data.csv"
df.to_csv(modified_file_path, index=False)

print(f"Modified dataset saved to {modified_file_path}")

import pandas as pd
import numpy as np

# Load the dataset
file_path = "/content/realistic_crispr_disease_data.csv"
df = pd.read_csv(file_path)

# Define realistic mappings for genes and their respective chromosomes
gene_chromosome_map = {
    'TP53': '17p13.1', 'CFTR': '7q31.2', 'EGFR': '7p11.2', 'BRCA1': '17q21.31',
    'BRCA2': '13q13.1', 'KRAS': '12p12.1', 'BRAF': '7q34', 'MYC': '8q24.21'
}

# Assign genes based on diseases (correlation)
disease_gene_map = {
    'Cystic Fibrosis': ['CFTR'], 'Lung Cancer': ['EGFR', 'KRAS', 'BRAF'],
    'Breast Cancer': ['BRCA1', 'BRCA2'], 'Colon Cancer': ['KRAS', 'BRAF'],
    'Leukemia': ['TP53', 'MYC'], 'None': ['TP53', 'BRCA2']
}
df['gene'] = df['disease'].apply(lambda d: np.random.choice(disease_gene_map.get(d, ['TP53', 'BRCA2'])))
df['chromosomal_location'] = df['gene'].map(gene_chromosome_map)

# Correlate mutation types and positions with genes
mutation_types = {
    'TP53': ['Missense', 'Nonsense', 'Frameshift'],
    'CFTR': ['Frameshift', 'Splice-site'],
    'EGFR': ['Missense', 'Insertion'],
    'BRCA1': ['Frameshift', 'Deletion'],
    'BRCA2': ['Splice-site', 'Nonsense'],
    'KRAS': ['Missense', 'Insertion'],
    'BRAF': ['Missense'],
    'MYC': ['Deletion']
}
df['mutation_type'] = df['gene'].apply(lambda g: np.random.choice(mutation_types[g]))
df['mutation_position'] = df['gene'].apply(lambda g: np.random.randint(100, 3000) if g in ['TP53', 'BRCA1'] else np.random.randint(500, 4000))

# Introduce real-world pathogenicity scores (0-1 probability)
df['pathogenicity_score'] = df['mutation_type'].apply(lambda m: np.random.uniform(0.1, 0.9) if m in ['Missense', 'Splice-site'] else np.random.uniform(0.5, 0.99)).round(2)

# Adjust efficiency scores based on mutation type and pathogenicity
df['efficiency_score'] = (1 - df['pathogenicity_score']) * np.random.uniform(0.5, 1.0)
df['efficiency_score'] = df['efficiency_score'].clip(0, 1).round(2)

# Adjust epigenetic markers with some missing values
df['epigenetic_marker'] = np.random.choice([1, 2, 3, np.nan], size=len(df), p=[0.3, 0.3, 0.3, 0.1])

# Introduce correlations between lifestyle factors and disease
smoking_impact = {'Never': 0.1, 'Former': 0.3, 'Current': 0.6}
df['smoking_history'] = np.random.choice(['Never', 'Former', 'Current'], size=len(df), p=[0.5, 0.3, 0.2])
df['exercise_frequency'] = np.random.choice(['Low', 'Moderate', 'High'], size=len(df), p=[0.3, 0.4, 0.3])
df['diet'] = np.random.choice(['Unhealthy', 'Moderate', 'Healthy'], size=len(df), p=[0.3, 0.4, 0.3])
df['pollution_level'] = np.random.choice(['Low', 'Medium', 'High'], size=len(df), p=[0.4, 0.4, 0.2])

# Disease correlation: Higher smoking & pollution, lower exercise → Higher disease risk
df['disease_risk'] = df.apply(lambda row:
    (smoking_impact[row['smoking_history']] * 0.5) +
    (0.3 if row['pollution_level'] == 'High' else 0.1) -
    (0.2 if row['exercise_frequency'] == 'High' else 0), axis=1
)

# Introduce missing values in some key columns
for col in ['mutation_type', 'gene', 'pathogenicity_score', 'efficiency_score', 'exercise_frequency', 'diet']:
    df.loc[df.sample(frac=0.05).index, col] = np.nan  # 5% missing values

# Adjust therapy feasibility based on pathogenicity & disease risk
df['gene_therapy_feasibility'] = df.apply(lambda row: 'High' if row['pathogenicity_score'] < 0.5 and row['disease_risk'] < 0.3 else 'Low', axis=1)

# Drop intermediate disease risk column (just for computation)
df.drop(columns=['disease_risk'], inplace=True)

# Save the modified dataset
modified_file_path = "/content/realistic_crispr_disease_data_correlated.csv"
df.to_csv(modified_file_path, index=False)

print(f"Modified dataset saved to {modified_file_path}")

import pandas as pd
import numpy as np

# Load the dataset
file_path = "/content/realistic_crispr_disease_data.csv"
df = pd.read_csv(file_path)

# Define realistic mappings for genes and their respective chromosomes
gene_chromosome_map = {
    'TP53': '17p13.1', 'CFTR': '7q31.2', 'EGFR': '7p11.2', 'BRCA1': '17q21.31',
    'BRCA2': '13q13.1', 'KRAS': '12p12.1', 'BRAF': '7q34', 'MYC': '8q24.21'
}

# Assign genes based on diseases
disease_gene_map = {
    'Cystic Fibrosis': ['CFTR'], 'Lung Cancer': ['EGFR', 'KRAS', 'BRAF'],
    'Breast Cancer': ['BRCA1', 'BRCA2'], 'Colon Cancer': ['KRAS', 'BRAF'],
    'Leukemia': ['TP53', 'MYC'], 'None': ['TP53', 'BRCA2']
}
df['gene'] = df['disease'].apply(lambda d: np.random.choice(disease_gene_map.get(d, ['TP53', 'BRCA2'])))
df['chromosomal_location'] = df['gene'].map(gene_chromosome_map)

# Correlate mutation types and positions with genes
mutation_types = {
    'TP53': ['Missense', 'Nonsense', 'Frameshift'],
    'CFTR': ['Frameshift', 'Splice-site'],
    'EGFR': ['Missense', 'Insertion'],
    'BRCA1': ['Frameshift', 'Deletion'],
    'BRCA2': ['Splice-site', 'Nonsense'],
    'KRAS': ['Missense', 'Insertion'],
    'BRAF': ['Missense'],
    'MYC': ['Deletion']
}
df['mutation_type'] = df['gene'].apply(lambda g: np.random.choice(mutation_types[g]))
df['mutation_position'] = df['gene'].apply(lambda g: np.random.randint(100, 3000) if g in ['TP53', 'BRCA1'] else np.random.randint(500, 4000))

# Pathogenicity scores
df['pathogenicity_score'] = df['mutation_type'].apply(lambda m: np.random.uniform(0.1, 0.9) if m in ['Missense', 'Splice-site'] else np.random.uniform(0.5, 0.99)).round(2)

# Efficiency scores
df['efficiency_score'] = (1 - df['pathogenicity_score']) * np.random.uniform(0.5, 1.0)
df['efficiency_score'] = df['efficiency_score'].clip(0, 1).round(2)

# Epigenetic markers with missing values
df['epigenetic_marker'] = np.random.choice([1, 2, 3, np.nan], size=len(df), p=[0.3, 0.3, 0.3, 0.1])

# Lifestyle factors
df['smoking_history'] = np.random.choice(['Never', 'Former', 'Current'], size=len(df), p=[0.5, 0.3, 0.2])
df['exercise_frequency'] = np.random.choice(['Low', 'Moderate', 'High'], size=len(df), p=[0.3, 0.4, 0.3])
df['diet'] = np.random.choice(['Unhealthy', 'Moderate', 'Healthy'], size=len(df), p=[0.3, 0.4, 0.3])
df['pollution_level'] = np.random.choice(['Low', 'Medium', 'High'], size=len(df), p=[0.4, 0.4, 0.2])

# 🔹 Adjust Drug Response Based on Smoking History
def determine_drug_response(smoking):
    if smoking == 'Current':
        return 'Ineffective'
    elif smoking == 'Former':
        return 'Moderate'
    return 'Effective'

df['drug_response'] = df['smoking_history'].apply(determine_drug_response)

# 🔹 Adjust Treatment Duration Based on Exercise
def determine_treatment_duration(exercise):
    if exercise == 'High':
        return 'Short'
    elif exercise == 'Moderate':
        return 'Normal'
    return 'Long'

df['treatment_duration'] = df['exercise_frequency'].apply(determine_treatment_duration)

# 🔹 Adjust Allergen Exposure Based on Pollution Levels
df['allergen_exposure'] = df['pollution_level'].apply(lambda p: 'High' if p == 'High' else 'Low')

# 🔹 Adjust Side Effects Based on Drug Response
df['side_effects'] = df['drug_response'].apply(lambda d: 'Severe' if d == 'Ineffective' else 'Mild')

# 🔹 Adjust Gene Therapy Feasibility Based on Lifestyle
def determine_feasibility(row):
    if row['smoking_history'] == 'Current' or row['diet'] == 'Unhealthy' or row['exercise_frequency'] == 'Low':
        return 'Low'
    return 'High'

df['gene_therapy_feasibility'] = df.apply(determine_feasibility, axis=1)

# Introduce missing values
for col in ['mutation_type', 'gene', 'pathogenicity_score', 'efficiency_score', 'exercise_frequency', 'diet']:
    df.loc[df.sample(frac=0.05).index, col] = np.nan

# Save the modified dataset
modified_file_path = "/content/realistic_crispr_data.csv"
df.to_csv(modified_file_path, index=False)

print(f"Modified dataset saved to {modified_file_path}")

