# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12LhGtr7M6Dv9W-40NDauNFla91ayMwfZ
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

# Load the dataset
file_path = "/content/synthetic_crispr_disease_data_realistic (1).csv"
df = pd.read_csv(file_path)

# Display basic info
print(df.info())
print(df.describe())

# Check for missing values
print("\nMissing values:\n", df.isnull().sum())

# Set Seaborn style
sns.set(style="whitegrid")

# Histogram of numerical columns
df.hist(figsize=(12, 8), bins=20, edgecolor="black")
plt.suptitle("Distribution of Numerical Features")
plt.show()

# Pairplot to visualize relationships
sns.pairplot(df, diag_kind='kde')
plt.show()

# Correlation heatmap
plt.figure(figsize=(10, 6))

# Select only numerical columns for correlation calculation
numerical_df = df.select_dtypes(include=np.number)
sns.heatmap(numerical_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

# Boxplot for detecting outliers
plt.figure(figsize=(12, 6))
sns.boxplot(data=df, orient="h", palette="Set2")
plt.title("Boxplot of Features")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = "/content/synthetic_crispr_disease_data_realistic (1).csv"
df = pd.read_csv(file_path)

# Display column names for reference
print("Columns in dataset:", df.columns)

# Assuming 'Disease' is the column indicating if a patient has a disease (adjust as needed)
disease_df = df[df['disease'] == 1]  # Filter patients who have the disease

# Set Seaborn style
sns.set(style="whitegrid")

# Age distribution of patients with disease
plt.figure(figsize=(10, 6))
sns.histplot(disease_df['age'], bins=20, kde=True, color='red')
plt.title("Age Distribution of Patients with Disease")
plt.xlabel("age")
plt.ylabel("Count")
plt.show()

# Countplot for habits (assuming 'Habits' is a categorical column)
if 'Habits' in df.columns:
    plt.figure(figsize=(10, 6))
    sns.countplot(x='Habits', data=disease_df, palette="Set2")
    plt.title("Habits of Patients with Disease")
    plt.xticks(rotation=45)
    plt.xlabel("Habits")
    plt.ylabel("Count")
    plt.show()

# Boxplot of age vs. habits (if habits exist)
if 'Habits' in df.columns:
    plt.figure(figsize=(12, 6))
    sns.boxplot(x='Habits', y='Age', data=disease_df, palette="coolwarm")
    plt.title("Age Distribution Across Different Habits (Patients with Disease)")
    plt.xticks(rotation=45)
    plt.xlabel("Habits")
    plt.ylabel("age")
    plt.show()

# Correlation heatmap for patients with disease
plt.figure(figsize=(10, 6))
sns.heatmap(disease_df.corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Heatmap (Patients with Disease)")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
file_path = "/content/synthetic_crispr_disease_data_realistic (1).csv"
df = pd.read_csv(file_path)

# Set Seaborn style
sns.set(style="whitegrid")

# 1️⃣ Histogram - Age distribution
plt.figure(figsize=(8, 5))
sns.histplot(df["age"], bins=20, kde=True, color="blue")
plt.title("Age Distribution")
plt.xlabel("Age")
plt.ylabel("Count")
plt.show()

# 2️⃣ Boxplot - Gene expression levels
plt.figure(figsize=(8, 5))
sns.boxplot(x=df["gene_expression"], color="green")
plt.title("Gene Expression Levels")
plt.xlabel("Gene Expression")
plt.show()

# 3️⃣ Bar Plot - Disease Distribution
plt.figure(figsize=(10, 5))
sns.countplot(y=df["disease"], order=df["disease"].value_counts().index, palette="coolwarm")
plt.title("Disease Distribution in Dataset")
plt.xlabel("Count")
plt.ylabel("Disease Type")
plt.show()

# 4️⃣ Scatter Plot - Gene Expression vs Mutation Position
plt.figure(figsize=(8, 5))
sns.scatterplot(x=df["mutation_position"], y=df["gene_expression"], hue=df["pathogenicity"], alpha=0.7)
plt.title("Gene Expression vs Mutation Position")
plt.xlabel("Mutation Position")
plt.ylabel("Gene Expression")
plt.legend(title="Pathogenicity")
plt.show()

# 5️⃣ Correlation Heatmap - Numerical Features
numerical_features = ["age", "gene_expression", "mutation_position", "treatment_duration"]
plt.figure(figsize=(8, 5))
sns.heatmap(df[numerical_features].corr(), annot=True, cmap="coolwarm", fmt=".2f")
plt.title("Feature Correlation Heatmap")
plt.show()

